apiVersion: v2
name: k8s-pod-mutator-webhook
description: >-
  Kubernetes Mutating Admission Webhook for Pods. Applies arbitrary changes to
  Pod manifests.
type: application
version: 0.2.0
# renovate depName=ghcr.io/anthr76/k8s-pod-mutator-webhook/webhook datasource=docker
appVersion: 1.5.1
sources:
  - https://github.com/anthr76/k8s-pod-mutator-webhook
